/* eslint-disable global-require */
/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/createIconsDocs.js.
 * Add synonyms in icon/icons/synonyms.js.
 */

import FileTypeArchive16Icon from '../glyph/file-type/archive/16';
import FileTypeArchive24Icon from '../glyph/file-type/archive/24';
import FileTypeArchive48Icon from '../glyph/file-type/archive/48';
import FileTypeAudio16Icon from '../glyph/file-type/audio/16';
import FileTypeAudio24Icon from '../glyph/file-type/audio/24';
import FileTypeAudio48Icon from '../glyph/file-type/audio/48';
import FileTypeDocument16Icon from '../glyph/file-type/document/16';
import FileTypeDocument24Icon from '../glyph/file-type/document/24';
import FileTypeDocument48Icon from '../glyph/file-type/document/48';
import FileTypeExcelSpreadsheet16Icon from '../glyph/file-type/excel-spreadsheet/16';
import FileTypeExcelSpreadsheet24Icon from '../glyph/file-type/excel-spreadsheet/24';
import FileTypeExcelSpreadsheet48Icon from '../glyph/file-type/excel-spreadsheet/48';
import FileTypeExecutable16Icon from '../glyph/file-type/executable/16';
import FileTypeExecutable24Icon from '../glyph/file-type/executable/24';
import FileTypeExecutable48Icon from '../glyph/file-type/executable/48';
import FileTypeFolder16Icon from '../glyph/file-type/folder/16';
import FileTypeFolder24Icon from '../glyph/file-type/folder/24';
import FileTypeFolder48Icon from '../glyph/file-type/folder/48';
import FileTypeGeneric16Icon from '../glyph/file-type/generic/16';
import FileTypeGeneric24Icon from '../glyph/file-type/generic/24';
import FileTypeGeneric48Icon from '../glyph/file-type/generic/48';
import FileTypeGif16Icon from '../glyph/file-type/gif/16';
import FileTypeGif24Icon from '../glyph/file-type/gif/24';
import FileTypeGif48Icon from '../glyph/file-type/gif/48';
import FileTypeGoogleDoc16Icon from '../glyph/file-type/google-doc/16';
import FileTypeGoogleDoc24Icon from '../glyph/file-type/google-doc/24';
import FileTypeGoogleDoc48Icon from '../glyph/file-type/google-doc/48';
import FileTypeGoogleForm16Icon from '../glyph/file-type/google-form/16';
import FileTypeGoogleForm24Icon from '../glyph/file-type/google-form/24';
import FileTypeGoogleForm48Icon from '../glyph/file-type/google-form/48';
import FileTypeGoogleSheet16Icon from '../glyph/file-type/google-sheet/16';
import FileTypeGoogleSheet24Icon from '../glyph/file-type/google-sheet/24';
import FileTypeGoogleSheet48Icon from '../glyph/file-type/google-sheet/48';
import FileTypeGoogleSlide16Icon from '../glyph/file-type/google-slide/16';
import FileTypeGoogleSlide24Icon from '../glyph/file-type/google-slide/24';
import FileTypeGoogleSlide48Icon from '../glyph/file-type/google-slide/48';
import FileTypeImage16Icon from '../glyph/file-type/image/16';
import FileTypeImage24Icon from '../glyph/file-type/image/24';
import FileTypeImage48Icon from '../glyph/file-type/image/48';
import FileTypePdfDocument16Icon from '../glyph/file-type/pdf-document/16';
import FileTypePdfDocument24Icon from '../glyph/file-type/pdf-document/24';
import FileTypePdfDocument48Icon from '../glyph/file-type/pdf-document/48';
import FileTypePowerpointPresentation16Icon from '../glyph/file-type/powerpoint-presentation/16';
import FileTypePowerpointPresentation24Icon from '../glyph/file-type/powerpoint-presentation/24';
import FileTypePowerpointPresentation48Icon from '../glyph/file-type/powerpoint-presentation/48';
import FileTypePresentation16Icon from '../glyph/file-type/presentation/16';
import FileTypePresentation24Icon from '../glyph/file-type/presentation/24';
import FileTypePresentation48Icon from '../glyph/file-type/presentation/48';
import FileTypeSketch16Icon from '../glyph/file-type/sketch/16';
import FileTypeSketch24Icon from '../glyph/file-type/sketch/24';
import FileTypeSketch48Icon from '../glyph/file-type/sketch/48';
import FileTypeSourceCode16Icon from '../glyph/file-type/source-code/16';
import FileTypeSourceCode24Icon from '../glyph/file-type/source-code/24';
import FileTypeSourceCode48Icon from '../glyph/file-type/source-code/48';
import FileTypeSpreadsheet16Icon from '../glyph/file-type/spreadsheet/16';
import FileTypeSpreadsheet24Icon from '../glyph/file-type/spreadsheet/24';
import FileTypeSpreadsheet48Icon from '../glyph/file-type/spreadsheet/48';
import FileTypeVideo16Icon from '../glyph/file-type/video/16';
import FileTypeVideo24Icon from '../glyph/file-type/video/24';
import FileTypeVideo48Icon from '../glyph/file-type/video/48';
import FileTypeWordDocument16Icon from '../glyph/file-type/word-document/16';
import FileTypeWordDocument24Icon from '../glyph/file-type/word-document/24';
import FileTypeWordDocument48Icon from '../glyph/file-type/word-document/48';
import ObjectBlog16Icon from '../glyph/object/blog/16';
import ObjectBlog24Icon from '../glyph/object/blog/24';
import ObjectBranch16Icon from '../glyph/object/branch/16';
import ObjectBranch24Icon from '../glyph/object/branch/24';
import ObjectBug16Icon from '../glyph/object/bug/16';
import ObjectBug24Icon from '../glyph/object/bug/24';
import ObjectCalendar16Icon from '../glyph/object/calendar/16';
import ObjectCalendar24Icon from '../glyph/object/calendar/24';
import ObjectChanges16Icon from '../glyph/object/changes/16';
import ObjectChanges24Icon from '../glyph/object/changes/24';
import ObjectCode16Icon from '../glyph/object/code/16';
import ObjectCode24Icon from '../glyph/object/code/24';
import ObjectCommit16Icon from '../glyph/object/commit/16';
import ObjectCommit24Icon from '../glyph/object/commit/24';
import ObjectEpic16Icon from '../glyph/object/epic/16';
import ObjectEpic24Icon from '../glyph/object/epic/24';
import ObjectImprovement16Icon from '../glyph/object/improvement/16';
import ObjectImprovement24Icon from '../glyph/object/improvement/24';
import ObjectIncident16Icon from '../glyph/object/incident/16';
import ObjectIncident24Icon from '../glyph/object/incident/24';
import ObjectIssue16Icon from '../glyph/object/issue/16';
import ObjectIssue24Icon from '../glyph/object/issue/24';
import ObjectNewFeature16Icon from '../glyph/object/new-feature/16';
import ObjectNewFeature24Icon from '../glyph/object/new-feature/24';
import ObjectPage16Icon from '../glyph/object/page/16';
import ObjectPage24Icon from '../glyph/object/page/24';
import ObjectProblem16Icon from '../glyph/object/problem/16';
import ObjectProblem24Icon from '../glyph/object/problem/24';
import ObjectQuestion16Icon from '../glyph/object/question/16';
import ObjectQuestion24Icon from '../glyph/object/question/24';
import ObjectRequest16Icon from '../glyph/object/request/16';
import ObjectRequest24Icon from '../glyph/object/request/24';
import ObjectStory16Icon from '../glyph/object/story/16';
import ObjectStory24Icon from '../glyph/object/story/24';
import ObjectSubtask16Icon from '../glyph/object/subtask/16';
import ObjectSubtask24Icon from '../glyph/object/subtask/24';
import ObjectTask16Icon from '../glyph/object/task/16';
import ObjectTask24Icon from '../glyph/object/task/24';

export default {
  'file-type/archive/16': {
    keywords: ['file-type/archive/16', 'filetypearchive16'],
    component: FileTypeArchive16Icon,
    componentName: 'FileTypeArchive16Icon',
    package: '@atlaskit/icon/glyph/file-type/archive/16',
  },
  'file-type/archive/24': {
    keywords: ['file-type/archive/24', 'filetypearchive24'],
    component: FileTypeArchive24Icon,
    componentName: 'FileTypeArchive24Icon',
    package: '@atlaskit/icon/glyph/file-type/archive/24',
  },
  'file-type/archive/48': {
    keywords: ['file-type/archive/48', 'filetypearchive48'],
    component: FileTypeArchive48Icon,
    componentName: 'FileTypeArchive48Icon',
    package: '@atlaskit/icon/glyph/file-type/archive/48',
  },
  'file-type/audio/16': {
    keywords: ['file-type/audio/16', 'filetypeaudio16'],
    component: FileTypeAudio16Icon,
    componentName: 'FileTypeAudio16Icon',
    package: '@atlaskit/icon/glyph/file-type/audio/16',
  },
  'file-type/audio/24': {
    keywords: ['file-type/audio/24', 'filetypeaudio24'],
    component: FileTypeAudio24Icon,
    componentName: 'FileTypeAudio24Icon',
    package: '@atlaskit/icon/glyph/file-type/audio/24',
  },
  'file-type/audio/48': {
    keywords: ['file-type/audio/48', 'filetypeaudio48'],
    component: FileTypeAudio48Icon,
    componentName: 'FileTypeAudio48Icon',
    package: '@atlaskit/icon/glyph/file-type/audio/48',
  },
  'file-type/document/16': {
    keywords: ['file-type/document/16', 'filetypedocument16'],
    component: FileTypeDocument16Icon,
    componentName: 'FileTypeDocument16Icon',
    package: '@atlaskit/icon/glyph/file-type/document/16',
  },
  'file-type/document/24': {
    keywords: ['file-type/document/24', 'filetypedocument24'],
    component: FileTypeDocument24Icon,
    componentName: 'FileTypeDocument24Icon',
    package: '@atlaskit/icon/glyph/file-type/document/24',
  },
  'file-type/document/48': {
    keywords: ['file-type/document/48', 'filetypedocument48'],
    component: FileTypeDocument48Icon,
    componentName: 'FileTypeDocument48Icon',
    package: '@atlaskit/icon/glyph/file-type/document/48',
  },
  'file-type/excel-spreadsheet/16': {
    keywords: ['file-type/excel-spreadsheet/16', 'filetypeexcelspreadsheet16'],
    component: FileTypeExcelSpreadsheet16Icon,
    componentName: 'FileTypeExcelSpreadsheet16Icon',
    package: '@atlaskit/icon/glyph/file-type/excel-spreadsheet/16',
  },
  'file-type/excel-spreadsheet/24': {
    keywords: ['file-type/excel-spreadsheet/24', 'filetypeexcelspreadsheet24'],
    component: FileTypeExcelSpreadsheet24Icon,
    componentName: 'FileTypeExcelSpreadsheet24Icon',
    package: '@atlaskit/icon/glyph/file-type/excel-spreadsheet/24',
  },
  'file-type/excel-spreadsheet/48': {
    keywords: ['file-type/excel-spreadsheet/48', 'filetypeexcelspreadsheet48'],
    component: FileTypeExcelSpreadsheet48Icon,
    componentName: 'FileTypeExcelSpreadsheet48Icon',
    package: '@atlaskit/icon/glyph/file-type/excel-spreadsheet/48',
  },
  'file-type/executable/16': {
    keywords: ['file-type/executable/16', 'filetypeexecutable16'],
    component: FileTypeExecutable16Icon,
    componentName: 'FileTypeExecutable16Icon',
    package: '@atlaskit/icon/glyph/file-type/executable/16',
  },
  'file-type/executable/24': {
    keywords: ['file-type/executable/24', 'filetypeexecutable24'],
    component: FileTypeExecutable24Icon,
    componentName: 'FileTypeExecutable24Icon',
    package: '@atlaskit/icon/glyph/file-type/executable/24',
  },
  'file-type/executable/48': {
    keywords: ['file-type/executable/48', 'filetypeexecutable48'],
    component: FileTypeExecutable48Icon,
    componentName: 'FileTypeExecutable48Icon',
    package: '@atlaskit/icon/glyph/file-type/executable/48',
  },
  'file-type/folder/16': {
    keywords: ['file-type/folder/16', 'filetypefolder16'],
    component: FileTypeFolder16Icon,
    componentName: 'FileTypeFolder16Icon',
    package: '@atlaskit/icon/glyph/file-type/folder/16',
  },
  'file-type/folder/24': {
    keywords: ['file-type/folder/24', 'filetypefolder24'],
    component: FileTypeFolder24Icon,
    componentName: 'FileTypeFolder24Icon',
    package: '@atlaskit/icon/glyph/file-type/folder/24',
  },
  'file-type/folder/48': {
    keywords: ['file-type/folder/48', 'filetypefolder48'],
    component: FileTypeFolder48Icon,
    componentName: 'FileTypeFolder48Icon',
    package: '@atlaskit/icon/glyph/file-type/folder/48',
  },
  'file-type/generic/16': {
    keywords: ['file-type/generic/16', 'filetypegeneric16'],
    component: FileTypeGeneric16Icon,
    componentName: 'FileTypeGeneric16Icon',
    package: '@atlaskit/icon/glyph/file-type/generic/16',
  },
  'file-type/generic/24': {
    keywords: ['file-type/generic/24', 'filetypegeneric24'],
    component: FileTypeGeneric24Icon,
    componentName: 'FileTypeGeneric24Icon',
    package: '@atlaskit/icon/glyph/file-type/generic/24',
  },
  'file-type/generic/48': {
    keywords: ['file-type/generic/48', 'filetypegeneric48'],
    component: FileTypeGeneric48Icon,
    componentName: 'FileTypeGeneric48Icon',
    package: '@atlaskit/icon/glyph/file-type/generic/48',
  },
  'file-type/gif/16': {
    keywords: ['file-type/gif/16', 'filetypegif16'],
    component: FileTypeGif16Icon,
    componentName: 'FileTypeGif16Icon',
    package: '@atlaskit/icon/glyph/file-type/gif/16',
  },
  'file-type/gif/24': {
    keywords: ['file-type/gif/24', 'filetypegif24'],
    component: FileTypeGif24Icon,
    componentName: 'FileTypeGif24Icon',
    package: '@atlaskit/icon/glyph/file-type/gif/24',
  },
  'file-type/gif/48': {
    keywords: ['file-type/gif/48', 'filetypegif48'],
    component: FileTypeGif48Icon,
    componentName: 'FileTypeGif48Icon',
    package: '@atlaskit/icon/glyph/file-type/gif/48',
  },
  'file-type/google-doc/16': {
    keywords: ['file-type/google-doc/16', 'filetypegoogledoc16'],
    component: FileTypeGoogleDoc16Icon,
    componentName: 'FileTypeGoogleDoc16Icon',
    package: '@atlaskit/icon/glyph/file-type/google-doc/16',
  },
  'file-type/google-doc/24': {
    keywords: ['file-type/google-doc/24', 'filetypegoogledoc24'],
    component: FileTypeGoogleDoc24Icon,
    componentName: 'FileTypeGoogleDoc24Icon',
    package: '@atlaskit/icon/glyph/file-type/google-doc/24',
  },
  'file-type/google-doc/48': {
    keywords: ['file-type/google-doc/48', 'filetypegoogledoc48'],
    component: FileTypeGoogleDoc48Icon,
    componentName: 'FileTypeGoogleDoc48Icon',
    package: '@atlaskit/icon/glyph/file-type/google-doc/48',
  },
  'file-type/google-form/16': {
    keywords: ['file-type/google-form/16', 'filetypegoogleform16'],
    component: FileTypeGoogleForm16Icon,
    componentName: 'FileTypeGoogleForm16Icon',
    package: '@atlaskit/icon/glyph/file-type/google-form/16',
  },
  'file-type/google-form/24': {
    keywords: ['file-type/google-form/24', 'filetypegoogleform24'],
    component: FileTypeGoogleForm24Icon,
    componentName: 'FileTypeGoogleForm24Icon',
    package: '@atlaskit/icon/glyph/file-type/google-form/24',
  },
  'file-type/google-form/48': {
    keywords: ['file-type/google-form/48', 'filetypegoogleform48'],
    component: FileTypeGoogleForm48Icon,
    componentName: 'FileTypeGoogleForm48Icon',
    package: '@atlaskit/icon/glyph/file-type/google-form/48',
  },
  'file-type/google-sheet/16': {
    keywords: ['file-type/google-sheet/16', 'filetypegooglesheet16'],
    component: FileTypeGoogleSheet16Icon,
    componentName: 'FileTypeGoogleSheet16Icon',
    package: '@atlaskit/icon/glyph/file-type/google-sheet/16',
  },
  'file-type/google-sheet/24': {
    keywords: ['file-type/google-sheet/24', 'filetypegooglesheet24'],
    component: FileTypeGoogleSheet24Icon,
    componentName: 'FileTypeGoogleSheet24Icon',
    package: '@atlaskit/icon/glyph/file-type/google-sheet/24',
  },
  'file-type/google-sheet/48': {
    keywords: ['file-type/google-sheet/48', 'filetypegooglesheet48'],
    component: FileTypeGoogleSheet48Icon,
    componentName: 'FileTypeGoogleSheet48Icon',
    package: '@atlaskit/icon/glyph/file-type/google-sheet/48',
  },
  'file-type/google-slide/16': {
    keywords: ['file-type/google-slide/16', 'filetypegoogleslide16'],
    component: FileTypeGoogleSlide16Icon,
    componentName: 'FileTypeGoogleSlide16Icon',
    package: '@atlaskit/icon/glyph/file-type/google-slide/16',
  },
  'file-type/google-slide/24': {
    keywords: ['file-type/google-slide/24', 'filetypegoogleslide24'],
    component: FileTypeGoogleSlide24Icon,
    componentName: 'FileTypeGoogleSlide24Icon',
    package: '@atlaskit/icon/glyph/file-type/google-slide/24',
  },
  'file-type/google-slide/48': {
    keywords: ['file-type/google-slide/48', 'filetypegoogleslide48'],
    component: FileTypeGoogleSlide48Icon,
    componentName: 'FileTypeGoogleSlide48Icon',
    package: '@atlaskit/icon/glyph/file-type/google-slide/48',
  },
  'file-type/image/16': {
    keywords: ['file-type/image/16', 'filetypeimage16'],
    component: FileTypeImage16Icon,
    componentName: 'FileTypeImage16Icon',
    package: '@atlaskit/icon/glyph/file-type/image/16',
  },
  'file-type/image/24': {
    keywords: ['file-type/image/24', 'filetypeimage24'],
    component: FileTypeImage24Icon,
    componentName: 'FileTypeImage24Icon',
    package: '@atlaskit/icon/glyph/file-type/image/24',
  },
  'file-type/image/48': {
    keywords: ['file-type/image/48', 'filetypeimage48'],
    component: FileTypeImage48Icon,
    componentName: 'FileTypeImage48Icon',
    package: '@atlaskit/icon/glyph/file-type/image/48',
  },
  'file-type/pdf-document/16': {
    keywords: ['file-type/pdf-document/16', 'filetypepdfdocument16'],
    component: FileTypePdfDocument16Icon,
    componentName: 'FileTypePdfDocument16Icon',
    package: '@atlaskit/icon/glyph/file-type/pdf-document/16',
  },
  'file-type/pdf-document/24': {
    keywords: ['file-type/pdf-document/24', 'filetypepdfdocument24'],
    component: FileTypePdfDocument24Icon,
    componentName: 'FileTypePdfDocument24Icon',
    package: '@atlaskit/icon/glyph/file-type/pdf-document/24',
  },
  'file-type/pdf-document/48': {
    keywords: ['file-type/pdf-document/48', 'filetypepdfdocument48'],
    component: FileTypePdfDocument48Icon,
    componentName: 'FileTypePdfDocument48Icon',
    package: '@atlaskit/icon/glyph/file-type/pdf-document/48',
  },
  'file-type/powerpoint-presentation/16': {
    keywords: [
      'file-type/powerpoint-presentation/16',
      'filetypepowerpointpresentation16',
    ],
    component: FileTypePowerpointPresentation16Icon,
    componentName: 'FileTypePowerpointPresentation16Icon',
    package: '@atlaskit/icon/glyph/file-type/powerpoint-presentation/16',
  },
  'file-type/powerpoint-presentation/24': {
    keywords: [
      'file-type/powerpoint-presentation/24',
      'filetypepowerpointpresentation24',
    ],
    component: FileTypePowerpointPresentation24Icon,
    componentName: 'FileTypePowerpointPresentation24Icon',
    package: '@atlaskit/icon/glyph/file-type/powerpoint-presentation/24',
  },
  'file-type/powerpoint-presentation/48': {
    keywords: [
      'file-type/powerpoint-presentation/48',
      'filetypepowerpointpresentation48',
    ],
    component: FileTypePowerpointPresentation48Icon,
    componentName: 'FileTypePowerpointPresentation48Icon',
    package: '@atlaskit/icon/glyph/file-type/powerpoint-presentation/48',
  },
  'file-type/presentation/16': {
    keywords: ['file-type/presentation/16', 'filetypepresentation16'],
    component: FileTypePresentation16Icon,
    componentName: 'FileTypePresentation16Icon',
    package: '@atlaskit/icon/glyph/file-type/presentation/16',
  },
  'file-type/presentation/24': {
    keywords: ['file-type/presentation/24', 'filetypepresentation24'],
    component: FileTypePresentation24Icon,
    componentName: 'FileTypePresentation24Icon',
    package: '@atlaskit/icon/glyph/file-type/presentation/24',
  },
  'file-type/presentation/48': {
    keywords: ['file-type/presentation/48', 'filetypepresentation48'],
    component: FileTypePresentation48Icon,
    componentName: 'FileTypePresentation48Icon',
    package: '@atlaskit/icon/glyph/file-type/presentation/48',
  },
  'file-type/sketch/16': {
    keywords: ['file-type/sketch/16', 'filetypesketch16'],
    component: FileTypeSketch16Icon,
    componentName: 'FileTypeSketch16Icon',
    package: '@atlaskit/icon/glyph/file-type/sketch/16',
  },
  'file-type/sketch/24': {
    keywords: ['file-type/sketch/24', 'filetypesketch24'],
    component: FileTypeSketch24Icon,
    componentName: 'FileTypeSketch24Icon',
    package: '@atlaskit/icon/glyph/file-type/sketch/24',
  },
  'file-type/sketch/48': {
    keywords: ['file-type/sketch/48', 'filetypesketch48'],
    component: FileTypeSketch48Icon,
    componentName: 'FileTypeSketch48Icon',
    package: '@atlaskit/icon/glyph/file-type/sketch/48',
  },
  'file-type/source-code/16': {
    keywords: ['file-type/source-code/16', 'filetypesourcecode16'],
    component: FileTypeSourceCode16Icon,
    componentName: 'FileTypeSourceCode16Icon',
    package: '@atlaskit/icon/glyph/file-type/source-code/16',
  },
  'file-type/source-code/24': {
    keywords: ['file-type/source-code/24', 'filetypesourcecode24'],
    component: FileTypeSourceCode24Icon,
    componentName: 'FileTypeSourceCode24Icon',
    package: '@atlaskit/icon/glyph/file-type/source-code/24',
  },
  'file-type/source-code/48': {
    keywords: ['file-type/source-code/48', 'filetypesourcecode48'],
    component: FileTypeSourceCode48Icon,
    componentName: 'FileTypeSourceCode48Icon',
    package: '@atlaskit/icon/glyph/file-type/source-code/48',
  },
  'file-type/spreadsheet/16': {
    keywords: ['file-type/spreadsheet/16', 'filetypespreadsheet16'],
    component: FileTypeSpreadsheet16Icon,
    componentName: 'FileTypeSpreadsheet16Icon',
    package: '@atlaskit/icon/glyph/file-type/spreadsheet/16',
  },
  'file-type/spreadsheet/24': {
    keywords: ['file-type/spreadsheet/24', 'filetypespreadsheet24'],
    component: FileTypeSpreadsheet24Icon,
    componentName: 'FileTypeSpreadsheet24Icon',
    package: '@atlaskit/icon/glyph/file-type/spreadsheet/24',
  },
  'file-type/spreadsheet/48': {
    keywords: ['file-type/spreadsheet/48', 'filetypespreadsheet48'],
    component: FileTypeSpreadsheet48Icon,
    componentName: 'FileTypeSpreadsheet48Icon',
    package: '@atlaskit/icon/glyph/file-type/spreadsheet/48',
  },
  'file-type/video/16': {
    keywords: ['file-type/video/16', 'filetypevideo16'],
    component: FileTypeVideo16Icon,
    componentName: 'FileTypeVideo16Icon',
    package: '@atlaskit/icon/glyph/file-type/video/16',
  },
  'file-type/video/24': {
    keywords: ['file-type/video/24', 'filetypevideo24'],
    component: FileTypeVideo24Icon,
    componentName: 'FileTypeVideo24Icon',
    package: '@atlaskit/icon/glyph/file-type/video/24',
  },
  'file-type/video/48': {
    keywords: ['file-type/video/48', 'filetypevideo48'],
    component: FileTypeVideo48Icon,
    componentName: 'FileTypeVideo48Icon',
    package: '@atlaskit/icon/glyph/file-type/video/48',
  },
  'file-type/word-document/16': {
    keywords: ['file-type/word-document/16', 'filetypeworddocument16'],
    component: FileTypeWordDocument16Icon,
    componentName: 'FileTypeWordDocument16Icon',
    package: '@atlaskit/icon/glyph/file-type/word-document/16',
  },
  'file-type/word-document/24': {
    keywords: ['file-type/word-document/24', 'filetypeworddocument24'],
    component: FileTypeWordDocument24Icon,
    componentName: 'FileTypeWordDocument24Icon',
    package: '@atlaskit/icon/glyph/file-type/word-document/24',
  },
  'file-type/word-document/48': {
    keywords: ['file-type/word-document/48', 'filetypeworddocument48'],
    component: FileTypeWordDocument48Icon,
    componentName: 'FileTypeWordDocument48Icon',
    package: '@atlaskit/icon/glyph/file-type/word-document/48',
  },
  'object/blog/16': {
    keywords: ['object/blog/16', 'objectblog16'],
    component: ObjectBlog16Icon,
    componentName: 'ObjectBlog16Icon',
    package: '@atlaskit/icon/glyph/object/blog/16',
  },
  'object/blog/24': {
    keywords: ['object/blog/24', 'objectblog24'],
    component: ObjectBlog24Icon,
    componentName: 'ObjectBlog24Icon',
    package: '@atlaskit/icon/glyph/object/blog/24',
  },
  'object/branch/16': {
    keywords: ['object/branch/16', 'objectbranch16'],
    component: ObjectBranch16Icon,
    componentName: 'ObjectBranch16Icon',
    package: '@atlaskit/icon/glyph/object/branch/16',
  },
  'object/branch/24': {
    keywords: ['object/branch/24', 'objectbranch24'],
    component: ObjectBranch24Icon,
    componentName: 'ObjectBranch24Icon',
    package: '@atlaskit/icon/glyph/object/branch/24',
  },
  'object/bug/16': {
    keywords: ['object/bug/16', 'objectbug16'],
    component: ObjectBug16Icon,
    componentName: 'ObjectBug16Icon',
    package: '@atlaskit/icon/glyph/object/bug/16',
  },
  'object/bug/24': {
    keywords: ['object/bug/24', 'objectbug24'],
    component: ObjectBug24Icon,
    componentName: 'ObjectBug24Icon',
    package: '@atlaskit/icon/glyph/object/bug/24',
  },
  'object/calendar/16': {
    keywords: ['object/calendar/16', 'objectcalendar16'],
    component: ObjectCalendar16Icon,
    componentName: 'ObjectCalendar16Icon',
    package: '@atlaskit/icon/glyph/object/calendar/16',
  },
  'object/calendar/24': {
    keywords: ['object/calendar/24', 'objectcalendar24'],
    component: ObjectCalendar24Icon,
    componentName: 'ObjectCalendar24Icon',
    package: '@atlaskit/icon/glyph/object/calendar/24',
  },
  'object/changes/16': {
    keywords: ['object/changes/16', 'objectchanges16'],
    component: ObjectChanges16Icon,
    componentName: 'ObjectChanges16Icon',
    package: '@atlaskit/icon/glyph/object/changes/16',
  },
  'object/changes/24': {
    keywords: ['object/changes/24', 'objectchanges24'],
    component: ObjectChanges24Icon,
    componentName: 'ObjectChanges24Icon',
    package: '@atlaskit/icon/glyph/object/changes/24',
  },
  'object/code/16': {
    keywords: ['object/code/16', 'objectcode16'],
    component: ObjectCode16Icon,
    componentName: 'ObjectCode16Icon',
    package: '@atlaskit/icon/glyph/object/code/16',
  },
  'object/code/24': {
    keywords: ['object/code/24', 'objectcode24'],
    component: ObjectCode24Icon,
    componentName: 'ObjectCode24Icon',
    package: '@atlaskit/icon/glyph/object/code/24',
  },
  'object/commit/16': {
    keywords: ['object/commit/16', 'objectcommit16'],
    component: ObjectCommit16Icon,
    componentName: 'ObjectCommit16Icon',
    package: '@atlaskit/icon/glyph/object/commit/16',
  },
  'object/commit/24': {
    keywords: ['object/commit/24', 'objectcommit24'],
    component: ObjectCommit24Icon,
    componentName: 'ObjectCommit24Icon',
    package: '@atlaskit/icon/glyph/object/commit/24',
  },
  'object/epic/16': {
    keywords: ['object/epic/16', 'objectepic16'],
    component: ObjectEpic16Icon,
    componentName: 'ObjectEpic16Icon',
    package: '@atlaskit/icon/glyph/object/epic/16',
  },
  'object/epic/24': {
    keywords: ['object/epic/24', 'objectepic24'],
    component: ObjectEpic24Icon,
    componentName: 'ObjectEpic24Icon',
    package: '@atlaskit/icon/glyph/object/epic/24',
  },
  'object/improvement/16': {
    keywords: ['object/improvement/16', 'objectimprovement16'],
    component: ObjectImprovement16Icon,
    componentName: 'ObjectImprovement16Icon',
    package: '@atlaskit/icon/glyph/object/improvement/16',
  },
  'object/improvement/24': {
    keywords: ['object/improvement/24', 'objectimprovement24'],
    component: ObjectImprovement24Icon,
    componentName: 'ObjectImprovement24Icon',
    package: '@atlaskit/icon/glyph/object/improvement/24',
  },
  'object/incident/16': {
    keywords: ['object/incident/16', 'objectincident16'],
    component: ObjectIncident16Icon,
    componentName: 'ObjectIncident16Icon',
    package: '@atlaskit/icon/glyph/object/incident/16',
  },
  'object/incident/24': {
    keywords: ['object/incident/24', 'objectincident24'],
    component: ObjectIncident24Icon,
    componentName: 'ObjectIncident24Icon',
    package: '@atlaskit/icon/glyph/object/incident/24',
  },
  'object/issue/16': {
    keywords: ['object/issue/16', 'objectissue16'],
    component: ObjectIssue16Icon,
    componentName: 'ObjectIssue16Icon',
    package: '@atlaskit/icon/glyph/object/issue/16',
  },
  'object/issue/24': {
    keywords: ['object/issue/24', 'objectissue24'],
    component: ObjectIssue24Icon,
    componentName: 'ObjectIssue24Icon',
    package: '@atlaskit/icon/glyph/object/issue/24',
  },
  'object/new-feature/16': {
    keywords: ['object/new-feature/16', 'objectnewfeature16'],
    component: ObjectNewFeature16Icon,
    componentName: 'ObjectNewFeature16Icon',
    package: '@atlaskit/icon/glyph/object/new-feature/16',
  },
  'object/new-feature/24': {
    keywords: ['object/new-feature/24', 'objectnewfeature24'],
    component: ObjectNewFeature24Icon,
    componentName: 'ObjectNewFeature24Icon',
    package: '@atlaskit/icon/glyph/object/new-feature/24',
  },
  'object/page/16': {
    keywords: ['object/page/16', 'objectpage16'],
    component: ObjectPage16Icon,
    componentName: 'ObjectPage16Icon',
    package: '@atlaskit/icon/glyph/object/page/16',
  },
  'object/page/24': {
    keywords: ['object/page/24', 'objectpage24'],
    component: ObjectPage24Icon,
    componentName: 'ObjectPage24Icon',
    package: '@atlaskit/icon/glyph/object/page/24',
  },
  'object/problem/16': {
    keywords: ['object/problem/16', 'objectproblem16'],
    component: ObjectProblem16Icon,
    componentName: 'ObjectProblem16Icon',
    package: '@atlaskit/icon/glyph/object/problem/16',
  },
  'object/problem/24': {
    keywords: ['object/problem/24', 'objectproblem24'],
    component: ObjectProblem24Icon,
    componentName: 'ObjectProblem24Icon',
    package: '@atlaskit/icon/glyph/object/problem/24',
  },
  'object/question/16': {
    keywords: ['object/question/16', 'objectquestion16'],
    component: ObjectQuestion16Icon,
    componentName: 'ObjectQuestion16Icon',
    package: '@atlaskit/icon/glyph/object/question/16',
  },
  'object/question/24': {
    keywords: ['object/question/24', 'objectquestion24'],
    component: ObjectQuestion24Icon,
    componentName: 'ObjectQuestion24Icon',
    package: '@atlaskit/icon/glyph/object/question/24',
  },
  'object/request/16': {
    keywords: ['object/request/16', 'objectrequest16'],
    component: ObjectRequest16Icon,
    componentName: 'ObjectRequest16Icon',
    package: '@atlaskit/icon/glyph/object/request/16',
  },
  'object/request/24': {
    keywords: ['object/request/24', 'objectrequest24'],
    component: ObjectRequest24Icon,
    componentName: 'ObjectRequest24Icon',
    package: '@atlaskit/icon/glyph/object/request/24',
  },
  'object/story/16': {
    keywords: ['object/story/16', 'objectstory16'],
    component: ObjectStory16Icon,
    componentName: 'ObjectStory16Icon',
    package: '@atlaskit/icon/glyph/object/story/16',
  },
  'object/story/24': {
    keywords: ['object/story/24', 'objectstory24'],
    component: ObjectStory24Icon,
    componentName: 'ObjectStory24Icon',
    package: '@atlaskit/icon/glyph/object/story/24',
  },
  'object/subtask/16': {
    keywords: ['object/subtask/16', 'objectsubtask16'],
    component: ObjectSubtask16Icon,
    componentName: 'ObjectSubtask16Icon',
    package: '@atlaskit/icon/glyph/object/subtask/16',
  },
  'object/subtask/24': {
    keywords: ['object/subtask/24', 'objectsubtask24'],
    component: ObjectSubtask24Icon,
    componentName: 'ObjectSubtask24Icon',
    package: '@atlaskit/icon/glyph/object/subtask/24',
  },
  'object/task/16': {
    keywords: ['object/task/16', 'objecttask16'],
    component: ObjectTask16Icon,
    componentName: 'ObjectTask16Icon',
    package: '@atlaskit/icon/glyph/object/task/16',
  },
  'object/task/24': {
    keywords: ['object/task/24', 'objecttask24'],
    component: ObjectTask24Icon,
    componentName: 'ObjectTask24Icon',
    package: '@atlaskit/icon/glyph/object/task/24',
  },
};
